/* SELECTED TOPIC */
export const SET_SELECTED_TOPIC = "SET_SELECTED_TOPICS";
export const ADD_SELECTED_TOPIC = "ADD_SELECTED_TOPIC";
export const DELETE_ONE_SELECTED_TOPIC = "DELETE_1_SE_TOPIC";
export const EMPTY_SELECTED_TOPICS = "EMPTY_SELECTED_TOPICS";

/* TESING PROPERTY */
export const SET_CREATED_TEST_INFO = "SET_CREATED_TEST_INFO";
export const UPDATE_CREATED_TEST_INFO = "UPDATE_CREATED_TEST_INFO";
export const GET_TOPIC_LIST = "GET_TOPIC_LIST";
//TOast
export const SET_SHOW_TOAST = "SET_SHOW_TOAST";
export const SET_CLOSE_TOAST = "SET_CLOSE_TOAST";


export const ADD_ANSWERD_QUESTION = "ADD_ANSWERD_QUESTION";
export const UPDATE_ANSWERD = "UPDATE_ANSWERD";

export const ADD_QUESTION_TO_TEST = "ADD_QUESTION_TO_TEST";
export const UPDATE_QUESTION_TO_TEST = "UPDATE_QUESTION_TO_TEST";
export const ADD_ANSWERD_TO_TEST = "ADD_ANSWERD_TO_TEST";
export const UPDATE_ANSWERD_TO_TEST = "UPDATE_ANSWERD_TO_TEST";
export const SET_NUMBER_CORRECT = "SET_NUMBER_CORRECT";
export const SET_TIME_FINNISH_TEST = "SET_TIME_FINNISH_TEST";
export const SET_NULL_FOR_ANSWERSET = "SET_NULL_FOR_ANSWERSET";
export const SET_ID_FOR_ANSWER = "SET_ID_FOR_ANSWER";
export const SET_LEVEL_OF_TEST = "SET_LEVEL_OF_TEST";

export const CLEAR_INFO_TEST = "CLEAR_INFO_TEST";

export const ADD_ANS_CORRECT_PER_TOPIC = "ADD_ANS_CORRECT_PER_TOPIC";

export const SET_END_TEST = "SET_END_TEST";
export const SET_START_TEST = "SET_START_TEST";

/* USER DETAIL PAGE */
export const SET_CURRENT_CHART = "SET_CURRENT_CHART";
export const GET_EVALUE_TOPICS_USER = "GET_EVALUE_TOPICS_USER";
export const SET_EVALUATED_CHART = "SET_EVALUATED_CHART";
export const CLEAR_EVALUATED_CHART = "CLEAR_EVALUATED_CHART";
