/* SELECTED TOPIC */
export const SET_SELECTED_TOPIC = "SET_SELECTED_TOPICS";
export const ADD_SELECTED_TOPIC = "ADD_SELECTED_TOPIC";
export const DELETE_ONE_SELECTED_TOPIC = "DELETE_1_SE_TOPIC";
export const EMPTY_SELECTED_TOPICS = "EMPTY_SELECTED_TOPICS";

/* TESING PROPERTY */
export const SET_CREATED_TEST_INFO = "SET_CREATED_TEST_INFO";
export const UPDATE_CREATED_TEST_INFO = "UPDATE_CREATED_TEST_INFO";

//TOast
export const SET_SHOW_TOAST = "SET_SHOW_TOAST";
export const SET_CLOSE_TOAST = "SET_CLOSE_TOAST";