/* SELECTED TOPIC */
export const SET_SELECTED_TOPIC = "SET_SELECTED_TOPICS";
export const ADD_SELECTED_TOPIC = "ADD_SELECTED_TOPIC";
export const DELETE_ONE_SELECTED_TOPIC = "DELETE_1_SE_TOPIC";
export const EMPTY_SELECTED_TOPICS = "EMPTY_SELECTED_TOPICS";

/* TESING PROPERTY */
export const SET_CREATED_TEST_INFO = "SET_CREATED_TEST_INFO";
export const UPDATE_CREATED_TEST_INFO = "UPDATE_CREATED_TEST_INFO";

export const ADD_ANSWERD_QUESTION = "ADD_ANSWERD_QUESTION";
export const UPDATE_ANSWERD = "UPDATE_ANSWERD";

export const ADD_QUESTION_TO_TEST = "ADD_QUESTION_TO_TEST";
export const UPDATE_QUESTION_TO_TEST = "UPDATE_QUESTION_TO_TEST";
export const ADD_ANSWERD_TO_TEST = "ADD_ANSWERD_TO_TEST";
export const UPDATE_ANSWERD_TO_TEST = "UPDATE_ANSWERD_TO_TEST";
export const SET_NUMBER_CORRECT = "SET_NUMBER_CORRECT";
export const SET_TIME_FINNISH_TEST = "SET_TIME_FINNISH_TEST";

export const CLEAR_INFO_TEST = "CLEAR_INFO_TEST";